[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "WAGIT"
version = "0.2.2"
description = "Automatic Git Push CLI"
authors = [
    { name="w4simg", email="w4simz@outlook.com" },
]
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "rich",
    "questionary",
    "requests",
    "groq"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
WAGIT = "wagit.cli:main"
